name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:


jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"

    - name: Run Go tests
      run: make test

    - name: Run Go vet
      run: make vet

    - name: Build
      run: go build -o bin/virtwork ./cmd/virtwork/...
