name: Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  image:
    name: image 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"

    - name: Login to Quay.io
      uses: docker/login-action@v4
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: quay.io/opdev/virtwork:dev
